version: '3.7'
services:

        service1:
                image: jadesola/service1
                build: ./service1
                ports:
                        - target: 5000
                          published: 5000
                          protocol: tcp
                depends_on:
                        - service2
                        - service3
                        - service4
                environment:
                        DATABASE_URI: ${DATABASE_URI}
                deploy:
                        replicas: 2 
       
        service2:
                image: jadesola/service2
                build: ./service2
                ports:
                        - target: 5001
                          published: 5001
                          protocol: tcp
                deploy:
                        replicas: 2
                          
        service3:
                image: jadesola/service3
                build: ./service3
                ports:
                        - target: 5002
                          published: 5002
                          protocol: tcp
                deploy:
                        replicas: 2

        service4:
                image: jadesola/service4
                build: ./service4
                ports:
                        - target: 5003
                          published: 5003
                          protocol: tcp
                deploy:
                        replicas: 2

