- name: "Update"
  apt:
    name:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg2
    - software-properties-common
    - python-pip
    - python3-pip
    update_cache: true
- name: "Install docker"
  pip:
    name:
    - docker
    - jsondiff
- name: "Get keys"
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: "Make repo"
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
    state: present
- name: "Install docker engine"
  apt:
    name: 
    - docker-ce
    - docker-ce-cli
    - containerd.io
    state: latest
    update_cache: true
- name: "add user to docker group"
  user:
    name: "{{ ansible_user }}"
    group: docker
    state: present  
